### PR TITLE
Added Typescript support.

### PR DESCRIPTION
**Pull request by ghost**
Haven't test it cause this site is a token grabber

### CODE REVIEW

**Comment by keksiqc** [comment]
> Haven't test it cause this site is a token grabber

Token grabber?

**Comment by ghost** [comment]
> > Haven't test it cause this site is a token grabber
> 
> Token grabber?

I guess

**Comment by ghost** [comment]
btw forgot to commit index.d.ts and other stuff.
Its in the pull request with the iconic name f

**Comment by keksiqc** [comment]
> > > Haven't test it cause this site is a token grabber
> > 
> > 
> > Token grabber?
> 
> I guess

You need to put your kawaii.red token there to use it

**Comment by keksiqc** [comment]
> btw forgot to commit index.d.ts and other stuff. Its in the pull request with the iconic name f

I have seen it, but I need to do some changes there.
But thank you

**Comment by ghost** [comment]
> > btw forgot to commit index.d.ts and other stuff. Its in the pull request with the iconic name f
> 
> I have seen it, but I need to do some changes there. But thank you

np

**Comment by Error4444** [comment]
Hey, @JamesBond-sys here is the creator of the API 👋. I can assure you that the site is not a token graber xD, the page only stores your user ID and then gives you a token to use the API. Otherwise, you can only write „anonymous“ instead of the token then you don’t even need to log in at all. 

More about that here: https://kawaii.red/information/

**Pull request closed without merging**
